#!/usr/bin/env bash
set -e

read -p "Enter your domain name: " DOMAIN
read -p "Enter your E-mail: " EMAIL
read -s -p "Enter the desired db password: " DBPASS
echo

sudo mariadb <<EOF
DROP DATABASE IF EXISTS wordpress;
DROP USER IF EXISTS 'wpuser'@'localhost';
CREATE DATABASE wordpress;
CREATE USER 'wpuser'@'localhost' IDENTIFIED BY '$DBPASS';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'localhost';
FLUSH PRIVILEGES;
EOF

# WordPress setup
sudo mkdir -p /srv/http/wordpress
cd /srv/http/wordpress
sudo wget -q https://wordpress.org/latest.zip
sudo unzip -q latest.zip
sudo mv wordpress my-site
sudo rm -f latest.zip
sudo chown -R http:http /srv/http/wordpress
sudo chmod -R 755 /srv/http/wordpress

# Nginx config
sudo mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled
sudo tee /etc/nginx/sites-available/wordpress > /dev/null <<EOL
server {
    listen 80;
    server_name menaouer.mooo.com;
    root /srv/http/wordpress/my-site;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
    }
}
EOL

sudo ln -sf /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/

# sudo sed -i '/http\s*{/a \    include /etc/nginx/sites-enabled/*;' /etc/nginx/nginx.conf
sudo sed -i '/^http[[:space:]]*{/,/^}/ { /^}/i\
    include /etc/nginx/sites-enabled/*;
}' /etc/nginx/nginx.conf

sudo nginx -t && sudo systemctl reload nginx

read -p "want to secure your domain with HTTPS? (y/n): " answer
if [[ "$answer" == "y" ]]; then
    echo "Certbot working..."
    # SSL with Certbot
    sudo certbot --nginx -d $DOMAIN -m $EMAIL --non-interactive --agree-tos
fi

echo "✅ WordPress installed. Visit: https://$DOMAIN"
